name: Build and Deploy

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: xtrem-craft-build
          path: ./dist
